import { StyleSheet } from "react-native";
import { colors } from "../../styles/globalStyles";

export const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: colors.background,
    flex: 1,
  },
  container: {
    marginTop: 70,
    alignItems: "center",
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 24,
    fontFamily: "Inter-Bold",
    width: "100%",
    borderBottomWidth: 0.2,
    height: 50,
    textAlign: "center",
    borderColor: "#98A2B3",
  },
  social_authContainer: {
    marginTop: 30,
    width: "100%",
    height: 170,
    justifyContent: "space-between",
    marginBottom: 20,
  },
  social_authButton: {
    flexDirection: "row",
    backgroundColor: "#FFF",
    width: "100%",
    height: 46,
    borderRadius: 8,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  socialButtonText: {
    marginLeft: 10,
    fontSize: 15,
    color: "#000",
    fontFamily: "Inter-Regular",
  },
  phone_authContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
  },
  selectCountry: {
    width: "30%",
    height: 52,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderRadius: 8,
    borderColor: "#C8C8C8",
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  phoneInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "68%",
    height: 52,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderRadius: 8,
    borderColor: "#C8C8C8",
    paddingHorizontal: 15,
  },
  countryCodeText: {
    fontSize: 17,
    marginRight: 8,
    fontFamily: "Inter-Regular",
  },
  flag: {
    fontSize: 20,
  },
  phoneInput: {
    fontSize: 17,
    height: 23,
    flex: 1,
    fontFamily: "Inter-Regular",
  },
  confirmButton: {
    backgroundColor: colors.primary,
    width: "100%",
    height: 48,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  contentContainer: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 25,
    paddingTop: 20,
  },
  countryItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    width: "100%",
  },
  flag: {
    fontSize: 20,
  },
  countryName: {
    fontSize: 15,
    fontFamily: "Inter-Regular",
  },
  countryCode: {
    fontSize: 16,
    color: "#888",
    fontFamily: "Inter-Regular",
  },
  separator: {
    height: 1,
    width: "100%",
    backgroundColor: "#E0E0E0",
  },
});
