export const services = [
  { key: "1", icon: "electricity", name: "Electricidad" },
  { key: "2", icon: "plumbing", name: "Plomeria" },
  { key: "3", icon: "gas", name: "Gas" },
  { key: "4", icon: "gardening", name: "Jardineria" },
  { key: "5", icon: "locksmith", name: "Cerrajeria" },
  { key: "6", icon: "painting", name: "Pintura" },
  { key: "7", icon: "construction", name: "Construccion" },
  { key: "8", icon: "pool", name: "Pileta" },
  { key: "9", icon: "carpentry", name: "Carpinteria" },
  { key: "10", icon: "glass", name: "Vidrios" },
  { key: "11", icon: "pets", name: "Mascotas" },
  { key: "12", icon: "security", name: "Seguridad" },
  { key: "13", icon: "ironwork", name: "Herreria" },
  { key: "14", icon: "technology", name: "Tecnologia" },
  { key: "15", icon: "beauty", name: "Belleza" },
  { key: "16", icon: "vehicles", name: "Vehiculos" },
  { key: "17", icon: "freight", name: "Fletes" },
  { key: "18", icon: "events", name: "Eventos" },
  { key: "19", icon: "photography", name: "Fotografia" },
  { key: "20", icon: "music", name: "Musica" },
];
